name: CI

on: push

jobs:
  build-and-test:
    name: Compile
    runs-on: ubuntu-latest
    container: 
      image: vaugus/opencv:4.7.0
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: make && ./main test

      - name: Clean
        run: make clean
