name: CI

on: push

jobs:
  build-and-test:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull OpenCV Docker image
        run: docker pull vaugus/opencv:4.6.0

      - name: Compile
        run: docker run --rm -i --name opencv -v $(pwd):/work vaugus/opencv:4.6.0 make

      - name: Test
        run: docker run --rm -i --name opencv -v $(pwd):/work vaugus/opencv:4.6.0 ./tests

      - name: Clean
        run: docker run --rm -i --name opencv -v $(pwd):/work vaugus/opencv:4.6.0 make clean

